name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM/clang-tidy
        run: choco install llvm --yes

      - name: Configure
        run: >
          cmake -B build
          -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-warnings-as-errors=*"

      - name: Build (includes clang-tidy)
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
